// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package billing

import (
	"uniauth-gf/api/billing"
	billingService "uniauth-gf/internal/service/billing"
)

type ControllerV1 struct {
	billingService *billingService.BillingService
}

func NewV1() billing.IBillingV1 {
	return &ControllerV1{
		billingService: billingService.NewBillingService(),
	}
}
