// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"uniauth-gf/internal/dao/internal"
)

// billingCostRecordsDao is the data access object for the table billing_cost_records.
// You can define custom methods on it to extend its functionality as needed.
type billingCostRecordsDao struct {
	*internal.BillingCostRecordsDao
}

var (
	// BillingCostRecords is a globally accessible object for table billing_cost_records operations.
	BillingCostRecords = billingCostRecordsDao{internal.NewBillingCostRecordsDao()}
)

// Add your custom methods and functionality below.
