// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"uniauth-gf/internal/dao/internal"
)

// configAutoQuotaPoolDao is the data access object for the table config_auto_quota_pool.
// You can define custom methods on it to extend its functionality as needed.
type configAutoQuotaPoolDao struct {
	*internal.ConfigAutoQuotaPoolDao
}

var (
	// ConfigAutoQuotaPool is a globally accessible object for table config_auto_quota_pool operations.
	ConfigAutoQuotaPool = configAutoQuotaPoolDao{internal.NewConfigAutoQuotaPoolDao()}
)

// Add your custom methods and functionality below.
