// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"uniauth-gf/internal/dao/internal"
)

// configSingleModelApproachDao is the data access object for the table config_single_model_approach.
// You can define custom methods on it to extend its functionality as needed.
type configSingleModelApproachDao struct {
	*internal.ConfigSingleModelApproachDao
}

var (
	// ConfigSingleModelApproach is a globally accessible object for table config_single_model_approach operations.
	ConfigSingleModelApproach = configSingleModelApproachDao{internal.NewConfigSingleModelApproachDao()}
)

// Add your custom methods and functionality below.
