// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"uniauth-gf/internal/dao/internal"
)

// configExchangeRateDao is the data access object for the table config_exchange_rate.
// You can define custom methods on it to extend its functionality as needed.
type configExchangeRateDao struct {
	*internal.ConfigExchangeRateDao
}

var (
	// ConfigExchangeRate is a globally accessible object for table config_exchange_rate operations.
	ConfigExchangeRate = configExchangeRateDao{internal.NewConfigExchangeRateDao()}
)

// Add your custom methods and functionality below.
