// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"uniauth-gf/internal/dao/internal"
)

// configInternationalizationDao is the data access object for the table config_internationalization.
// You can define custom methods on it to extend its functionality as needed.
type configInternationalizationDao struct {
	*internal.ConfigInternationalizationDao
}

var (
	// ConfigInternationalization is a globally accessible object for table config_internationalization operations.
	ConfigInternationalization = configInternationalizationDao{internal.NewConfigInternationalizationDao()}
)

// Add your custom methods and functionality below.
