// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"uniauth-gf/internal/dao/internal"
)

// quotapoolQuotaPoolDao is the data access object for the table quotapool_quota_pool.
// You can define custom methods on it to extend its functionality as needed.
type quotapoolQuotaPoolDao struct {
	*internal.QuotapoolQuotaPoolDao
}

var (
	// QuotapoolQuotaPool is a globally accessible object for table quotapool_quota_pool operations.
	QuotapoolQuotaPool = quotapoolQuotaPoolDao{internal.NewQuotapoolQuotaPoolDao()}
)

// Add your custom methods and functionality below.
