// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"uniauth-gf/internal/dao/internal"
)

// userinfosUserInfosDao is the data access object for the table userinfos_user_infos.
// You can define custom methods on it to extend its functionality as needed.
type userinfosUserInfosDao struct {
	*internal.UserinfosUserInfosDao
}

var (
	// UserinfosUserInfos is a globally accessible object for table userinfos_user_infos operations.
	UserinfosUserInfos = userinfosUserInfosDao{internal.NewUserinfosUserInfosDao()}
)

// Add your custom methods and functionality below.
