// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"uniauth-gf/internal/dao/internal"
)

// userInfosDao is the data access object for the table user_infos.
// You can define custom methods on it to extend its functionality as needed.
type userInfosDao struct {
	*internal.UserInfosDao
}

var (
	// UserInfos is a globally accessible object for table user_infos operations.
	UserInfos = userInfosDao{internal.NewUserInfosDao()}
)

// Add your custom methods and functionality below.
