// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package auth

import (
	casbinService "uniauth-gf/internal/service/casbin"

	"github.com/casbin/casbin/v2"
)

var e *casbin.Enforcer

func init() {
	e = casbinService.GetEnforcer()
}
