// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package auth

import (
	"fmt"
	//pgadapter "github.com/casbin/casbin-pg-adapter"
	"github.com/casbin/casbin/v2"
	"github.com/casbin/casbin/v2/persist/file-adapter"
	"github.com/gogf/gf/v2/os/gres"
)

var e *casbin.Enforcer

func init() {
	gres.Dump()
	// File Adapter
	a := fileadapter.NewAdapter("resource/config/casbin_policy.csv")
	// PG Adapter
	// a, _ := pgadapter.NewAdapter("postgresql://uniauth:'It@73333!'@localhost:5432/uniauth")
	e, _ = casbin.NewEnforcer("resource/config/core_rbac.conf", a)
	if err := e.LoadPolicy(); err != nil {
		panic(err)
	}
	policies, _ := e.GetPolicy()
	fmt.Println(policies)
}
