// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package quotaPool

import (
	"uniauth-gf/api/quotaPool"
)

type ControllerV1 struct{}

func NewV1() quotaPool.IQuotaPoolV1 {
	return &ControllerV1{}
}
