# https://goframe.org/docs/web/server-config-file-template
server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# https://goframe.org/docs/core/glog-config
logger:
  level : "info"
  stdout: true

# https://goframe.org/docs/core/gdb-config-file
database:
  default:    
    link: "pgsql:uniauth:It@73333!@tcp(127.0.0.1:5432)/uniauth"
    createdAt: "created_at"     
    updatedAt: "updated_at" 

casbin:
  default:
    link: "postgresql://uniauth:It@73333!@127.0.0.1:5432/uniauth?sslmode=disable"
    database: "uniauth"