// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package autoquotapool

import (
	"uniauth-gf/api/autoquotapool"
)

type ControllerV1 struct{}

func NewV1() autoquotapool.IAutoquotapoolV1 {
	return &ControllerV1{}
}
