/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 */

import { customApiMutator } from "../utils/api-mutator";
import type {
  UniauthGfApiAuthV1AddGroupingReq,
  UniauthGfApiAuthV1AddGroupingRes,
  UniauthGfApiAuthV1AddPoliciesReq,
  UniauthGfApiAuthV1AddPoliciesRes,
  UniauthGfApiAuthV1DeleteGroupingReq,
  UniauthGfApiAuthV1DeleteGroupingRes,
  UniauthGfApiAuthV1DeletePoliciesReq,
  UniauthGfApiAuthV1DeletePoliciesRes,
  UniauthGfApiAuthV1EditGroupingReq,
  UniauthGfApiAuthV1EditGroupingRes,
  UniauthGfApiAuthV1EditPolicyReq,
  UniauthGfApiAuthV1EditPolicyRes,
} from "./uniauth.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getAuthAdminCrud = () => {
  /**
   * 允许批量添加 Grouping Policies。
   * @summary 添加 Grouping Policies
   */
  const postAuthAdminGroupingsAdd = (
    uniauthGfApiAuthV1AddGroupingReq: UniauthGfApiAuthV1AddGroupingReq,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiAuthV1AddGroupingRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiAuthV1AddGroupingRes>(
      {
        url: `/auth/admin/groupings/add`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: uniauthGfApiAuthV1AddGroupingReq,
      },
      options,
    );
  };
  /**
   * 允许批量删除 Grouping Policies。原子性操作，当规则中有一条和数据库中的规则不匹配，立即回滚所有操作并返回错误。
   * @summary 删除 Grouping Policies
   */
  const postAuthAdminGroupingsDelete = (
    uniauthGfApiAuthV1DeleteGroupingReq: UniauthGfApiAuthV1DeleteGroupingReq,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiAuthV1DeleteGroupingRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiAuthV1DeleteGroupingRes>(
      {
        url: `/auth/admin/groupings/delete`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: uniauthGfApiAuthV1DeleteGroupingReq,
      },
      options,
    );
  };
  /**
   * 编辑 Grouping Policies。需要提供老的 Grouping。
   * @summary 编辑 Grouping Policies
   */
  const postAuthAdminGroupingsEdit = (
    uniauthGfApiAuthV1EditGroupingReq: UniauthGfApiAuthV1EditGroupingReq,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiAuthV1EditGroupingRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiAuthV1EditGroupingRes>(
      {
        url: `/auth/admin/groupings/edit`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: uniauthGfApiAuthV1EditGroupingReq,
      },
      options,
    );
  };
  /**
   * @summary 添加 Policies
   */
  const postAuthAdminPoliciesAdd = (
    uniauthGfApiAuthV1AddPoliciesReq: UniauthGfApiAuthV1AddPoliciesReq,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiAuthV1AddPoliciesRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiAuthV1AddPoliciesRes>(
      {
        url: `/auth/admin/policies/add`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: uniauthGfApiAuthV1AddPoliciesReq,
      },
      options,
    );
  };
  /**
   * 删除 Policies。原子性操作，当规则中有一条和数据库中的规则不匹配，立即回滚所有操作并返回错误。
   * @summary 删除 Policies
   */
  const postAuthAdminPoliciesDelete = (
    uniauthGfApiAuthV1DeletePoliciesReq: UniauthGfApiAuthV1DeletePoliciesReq,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiAuthV1DeletePoliciesRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiAuthV1DeletePoliciesRes>(
      {
        url: `/auth/admin/policies/delete`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: uniauthGfApiAuthV1DeletePoliciesReq,
      },
      options,
    );
  };
  /**
   * 编辑 Policy。需要提供老的 Policy。<br>注意顺序是 Sub Obj Act。
   * @summary 编辑 Policy
   */
  const postAuthAdminPoliciesEdit = (
    uniauthGfApiAuthV1EditPolicyReq: UniauthGfApiAuthV1EditPolicyReq,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiAuthV1EditPolicyRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiAuthV1EditPolicyRes>(
      {
        url: `/auth/admin/policies/edit`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: uniauthGfApiAuthV1EditPolicyReq,
      },
      options,
    );
  };
  return {
    postAuthAdminGroupingsAdd,
    postAuthAdminGroupingsDelete,
    postAuthAdminGroupingsEdit,
    postAuthAdminPoliciesAdd,
    postAuthAdminPoliciesDelete,
    postAuthAdminPoliciesEdit,
  };
};
export type PostAuthAdminGroupingsAddResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getAuthAdminCrud>["postAuthAdminGroupingsAdd"]>
  >
>;
export type PostAuthAdminGroupingsDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getAuthAdminCrud>["postAuthAdminGroupingsDelete"]
    >
  >
>;
export type PostAuthAdminGroupingsEditResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getAuthAdminCrud>["postAuthAdminGroupingsEdit"]
    >
  >
>;
export type PostAuthAdminPoliciesAddResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getAuthAdminCrud>["postAuthAdminPoliciesAdd"]>
  >
>;
export type PostAuthAdminPoliciesDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getAuthAdminCrud>["postAuthAdminPoliciesDelete"]
    >
  >
>;
export type PostAuthAdminPoliciesEditResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getAuthAdminCrud>["postAuthAdminPoliciesEdit"]>
  >
>;
