/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 */

import { customApiMutator } from "../utils/api-mutator";
import type {
  UniauthGfApiAuthV1ChatPreCheckOneStopReq,
  UniauthGfApiAuthV1ChatPreCheckOneStopRes,
} from "./uniauth.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getAuthChat = () => {
  /**
   * 对话服务开启计费流程前的一站式权限检查，会进行以下检查：<br>1. 检查配额池是否存在；<br>2. 检查配额池是否被禁用；<br>3. 检查用户有没有权限使用这个配额池；<br>4. 检查配额池有没有权限使用这个 Svc 和 Product。
   * @summary 对话服务一站式权限预检查
   */
  const postAuthChatOneStop = (
    uniauthGfApiAuthV1ChatPreCheckOneStopReq: UniauthGfApiAuthV1ChatPreCheckOneStopReq,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiAuthV1ChatPreCheckOneStopRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiAuthV1ChatPreCheckOneStopRes>(
      {
        url: `/auth/chat/oneStop`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: uniauthGfApiAuthV1ChatPreCheckOneStopReq,
      },
      options,
    );
  };
  return { postAuthChatOneStop };
};
export type PostAuthChatOneStopResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuthChat>["postAuthChatOneStop"]>>
>;
