/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 */

import { customApiMutator } from "../utils/api-mutator";
import type {
  UniauthGfApiAuthV1UniauthLoginReq,
  UniauthGfApiAuthV1UniauthLoginRes,
} from "./uniauth.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getAuthUniauth = () => {
  /**
   * UniAuth账号密码校验
   * @summary UniAuth账号密码校验
   */
  const postAuthUniauthLogin = (
    uniauthGfApiAuthV1UniauthLoginReq: UniauthGfApiAuthV1UniauthLoginReq,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiAuthV1UniauthLoginRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiAuthV1UniauthLoginRes>(
      {
        url: `/auth/uniauth/login`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: uniauthGfApiAuthV1UniauthLoginReq,
      },
      options,
    );
  };
  return { postAuthUniauthLogin };
};
export type PostAuthUniauthLoginResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuthUniauth>["postAuthUniauthLogin"]>>
>;
