/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 */

import { customApiMutator } from "../utils/api-mutator";
import type {
  GetBillingStatsChatUsageChartParams,
  GetBillingStatsChatUsageGroupParams,
  UniauthGfApiBillingV1NDaysProductUsageChartRes,
  UniauthGfApiBillingV1NDaysProductUsageGroupRes,
} from "./uniauth.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getBillingStats = () => {
  /**
   * 可以传入最近N天参数。
   * @summary 对话服务产品使用次数统计接口（详细）
   */
  const getBillingStatsChatUsageChart = (
    params?: GetBillingStatsChatUsageChartParams,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiBillingV1NDaysProductUsageChartRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiBillingV1NDaysProductUsageChartRes>(
      { url: `/billing/stats/chat/usage/chart`, method: "GET", params },
      options,
    );
  };
  /**
   * 可以传入最近N天参数。
   * @summary 对话服务产品使用次数统计接口（聚合）
   */
  const getBillingStatsChatUsageGroup = (
    params?: GetBillingStatsChatUsageGroupParams,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiBillingV1NDaysProductUsageGroupRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiBillingV1NDaysProductUsageGroupRes>(
      { url: `/billing/stats/chat/usage/group`, method: "GET", params },
      options,
    );
  };
  return { getBillingStatsChatUsageChart, getBillingStatsChatUsageGroup };
};
export type GetBillingStatsChatUsageChartResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getBillingStats>["getBillingStatsChatUsageChart"]
    >
  >
>;
export type GetBillingStatsChatUsageGroupResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getBillingStats>["getBillingStatsChatUsageGroup"]
    >
  >
>;
