/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 */

import { customApiMutator } from "../utils/api-mutator";
import type {
  UniauthGfApiBillingV1BillingRecordReq,
  UniauthGfApiBillingV1BillingRecordRes,
  UniauthGfApiBillingV1CheckBalanceReq,
  UniauthGfApiBillingV1CheckBalanceRes,
  UniauthGfApiBillingV1CheckTokensUsageReq,
  UniauthGfApiBillingV1CheckTokensUsageRes,
  UniauthGfApiBillingV1GetBillingOptionsReq,
  UniauthGfApiBillingV1GetBillingOptionsRes,
} from "./uniauth.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getBilling = () => {
  /**
   * 刷新、检查配额池的余额。
   * @summary 检查余额
   */
  const postBillingCheck = (
    uniauthGfApiBillingV1CheckBalanceReq: UniauthGfApiBillingV1CheckBalanceReq,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiBillingV1CheckBalanceRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiBillingV1CheckBalanceRes>(
      {
        url: `/billing/check`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: uniauthGfApiBillingV1CheckBalanceReq,
      },
      options,
    );
  };
  /**
   * 检查Tokens使用情况
   * @summary 检查Tokens使用情况
   */
  const postBillingCheckTokensUsage = (
    uniauthGfApiBillingV1CheckTokensUsageReq: UniauthGfApiBillingV1CheckTokensUsageReq,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiBillingV1CheckTokensUsageRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiBillingV1CheckTokensUsageRes>(
      {
        url: `/billing/checkTokensUsage`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: uniauthGfApiBillingV1CheckTokensUsageReq,
      },
      options,
    );
  };
  /**
   * 获取指定配额池的所有服务和产品类型选项
   * @summary 获取计费选项
   */
  const postBillingOptions = (
    uniauthGfApiBillingV1GetBillingOptionsReq: UniauthGfApiBillingV1GetBillingOptionsReq,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiBillingV1GetBillingOptionsRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiBillingV1GetBillingOptionsRes>(
      {
        url: `/billing/options`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: uniauthGfApiBillingV1GetBillingOptionsReq,
      },
      options,
    );
  };
  /**
   * 上传计费请求，完成配额池的扣费。
   * @summary 计费接口
   */
  const postBillingRecord = (
    uniauthGfApiBillingV1BillingRecordReq: UniauthGfApiBillingV1BillingRecordReq,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiBillingV1BillingRecordRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiBillingV1BillingRecordRes>(
      {
        url: `/billing/record`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: uniauthGfApiBillingV1BillingRecordReq,
      },
      options,
    );
  };
  return {
    postBillingCheck,
    postBillingCheckTokensUsage,
    postBillingOptions,
    postBillingRecord,
  };
};
export type PostBillingCheckResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getBilling>["postBillingCheck"]>>
>;
export type PostBillingCheckTokensUsageResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getBilling>["postBillingCheckTokensUsage"]>
  >
>;
export type PostBillingOptionsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getBilling>["postBillingOptions"]>>
>;
export type PostBillingRecordResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getBilling>["postBillingRecord"]>>
>;
