/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 */

import { customApiMutator } from "../utils/api-mutator";
import type {
  UniauthGfApiBillingV1ExportBillRecordReq,
  UniauthGfApiBillingV1ExportBillRecordRes,
  UniauthGfApiBillingV1GetBillRecordReq,
  UniauthGfApiBillingV1GetBillRecordRes,
} from "./uniauth.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getBillingAdmin = () => {
  /**
   * 导出账单，根据一定的条件。有两个类型的账单，需要指定 type：<br>1. type = qp，返回每个配额池名下特定upns相关的账单；<br>2. type = upn，返回每个upn名下这些特定qps相关的账单。<br>数组传空时，则忽略对应的限制。
   * @summary 导出账单
   */
  const postBillingAdminExport = (
    uniauthGfApiBillingV1ExportBillRecordReq: UniauthGfApiBillingV1ExportBillRecordReq,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiBillingV1ExportBillRecordRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiBillingV1ExportBillRecordRes>(
      {
        url: `/billing/admin/export`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: uniauthGfApiBillingV1ExportBillRecordReq,
      },
      options,
    );
  };
  /**
   * 查询账单，根据一定的条件。有两个类型的账单，需要指定 type：<br>1. type = qp，返回每个配额池名下特定upns相关的账单；<br>2. type = upn，返回每个upn名下这些特定qps相关的账单。<br>数组传空时，则忽略对应的限制。
   * @summary 查询账单
   */
  const postBillingAdminGet = (
    uniauthGfApiBillingV1GetBillRecordReq: UniauthGfApiBillingV1GetBillRecordReq,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiBillingV1GetBillRecordRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiBillingV1GetBillRecordRes>(
      {
        url: `/billing/admin/get`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: uniauthGfApiBillingV1GetBillRecordReq,
      },
      options,
    );
  };
  return { postBillingAdminExport, postBillingAdminGet };
};
export type PostBillingAdminExportResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getBillingAdmin>["postBillingAdminExport"]>
  >
>;
export type PostBillingAdminGetResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getBillingAdmin>["postBillingAdminGet"]>>
>;
