/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 */

import { customApiMutator } from "../utils/api-mutator";
import type {
  DeleteConfigAutoConfigParams,
  UniauthGfApiConfigV1AddAutoQuotaPoolConfigReq,
  UniauthGfApiConfigV1AddAutoQuotaPoolConfigRes,
  UniauthGfApiConfigV1DeleteAutoQuotaPoolConfigRes,
  UniauthGfApiConfigV1EditAutoQuotaPoolConfigReq,
  UniauthGfApiConfigV1EditAutoQuotaPoolConfigRes,
  UniauthGfApiConfigV1GetAutoQuotaPoolConfigRes,
  UniauthGfApiConfigV1SyncAutoQuotaPoolUpnsCacheReq,
  UniauthGfApiConfigV1SyncAutoQuotaPoolUpnsCacheRes,
} from "./uniauth.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getConfigAutoquotapoolconfig = () => {
  /**
   * @summary 删除自动配额池规则
   */
  const deleteConfigAutoConfig = (
    params: DeleteConfigAutoConfigParams,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiConfigV1DeleteAutoQuotaPoolConfigRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiConfigV1DeleteAutoQuotaPoolConfigRes>(
      { url: `/config/autoConfig`, method: "DELETE", params },
      options,
    );
  };
  /**
   * @summary 获取自动配额池规则
   */
  const getConfigAutoConfig = (
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiConfigV1GetAutoQuotaPoolConfigRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiConfigV1GetAutoQuotaPoolConfigRes>(
      { url: `/config/autoConfig`, method: "GET" },
      options,
    );
  };
  /**
   * @summary 新增自动配额池规则
   */
  const postConfigAutoConfig = (
    uniauthGfApiConfigV1AddAutoQuotaPoolConfigReq: UniauthGfApiConfigV1AddAutoQuotaPoolConfigReq,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiConfigV1AddAutoQuotaPoolConfigRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiConfigV1AddAutoQuotaPoolConfigRes>(
      {
        url: `/config/autoConfig`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: uniauthGfApiConfigV1AddAutoQuotaPoolConfigReq,
      },
      options,
    );
  };
  /**
   * @summary 编辑自动配额池规则
   */
  const putConfigAutoConfig = (
    uniauthGfApiConfigV1EditAutoQuotaPoolConfigReq: UniauthGfApiConfigV1EditAutoQuotaPoolConfigReq,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiConfigV1EditAutoQuotaPoolConfigRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiConfigV1EditAutoQuotaPoolConfigRes>(
      {
        url: `/config/autoConfig`,
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        data: uniauthGfApiConfigV1EditAutoQuotaPoolConfigReq,
      },
      options,
    );
  };
  /**
   * @summary 手动同步自动配额池规则的 upns_cache
   */
  const postConfigAutoConfigSyncUpnsCache = (
    uniauthGfApiConfigV1SyncAutoQuotaPoolUpnsCacheReq: UniauthGfApiConfigV1SyncAutoQuotaPoolUpnsCacheReq,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiConfigV1SyncAutoQuotaPoolUpnsCacheRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiConfigV1SyncAutoQuotaPoolUpnsCacheRes>(
      {
        url: `/config/autoConfig/syncUpnsCache`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: uniauthGfApiConfigV1SyncAutoQuotaPoolUpnsCacheReq,
      },
      options,
    );
  };
  return {
    deleteConfigAutoConfig,
    getConfigAutoConfig,
    postConfigAutoConfig,
    putConfigAutoConfig,
    postConfigAutoConfigSyncUpnsCache,
  };
};
export type DeleteConfigAutoConfigResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getConfigAutoquotapoolconfig>["deleteConfigAutoConfig"]
    >
  >
>;
export type GetConfigAutoConfigResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getConfigAutoquotapoolconfig>["getConfigAutoConfig"]
    >
  >
>;
export type PostConfigAutoConfigResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getConfigAutoquotapoolconfig>["postConfigAutoConfig"]
    >
  >
>;
export type PutConfigAutoConfigResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getConfigAutoquotapoolconfig>["putConfigAutoConfig"]
    >
  >
>;
export type PostConfigAutoConfigSyncUpnsCacheResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getConfigAutoquotapoolconfig
      >["postConfigAutoConfigSyncUpnsCache"]
    >
  >
>;
