/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 */

import { customApiMutator } from "../utils/api-mutator";
import type {
  DeleteConfigModelParams,
  UniauthGfApiConfigV1AddModelConfigReq,
  UniauthGfApiConfigV1AddModelConfigRes,
  UniauthGfApiConfigV1DeleteModelConfigRes,
  UniauthGfApiConfigV1EditModelConfigReq,
  UniauthGfApiConfigV1EditModelConfigRes,
  UniauthGfApiConfigV1GetModelConfigRes,
} from "./uniauth.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getConfigModel = () => {
  /**
   * @summary 删除模型配置
   */
  const deleteConfigModel = (
    params?: DeleteConfigModelParams,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiConfigV1DeleteModelConfigRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiConfigV1DeleteModelConfigRes>(
      { url: `/config/model`, method: "DELETE", params },
      options,
    );
  };
  /**
   * @summary 添加模型配置
   */
  const postConfigModel = (
    uniauthGfApiConfigV1AddModelConfigReq: UniauthGfApiConfigV1AddModelConfigReq,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiConfigV1AddModelConfigRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiConfigV1AddModelConfigRes>(
      {
        url: `/config/model`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: uniauthGfApiConfigV1AddModelConfigReq,
      },
      options,
    );
  };
  /**
   * 编辑模型配置。
   * @summary 编辑模型配置
   */
  const putConfigModel = (
    uniauthGfApiConfigV1EditModelConfigReq: UniauthGfApiConfigV1EditModelConfigReq,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiConfigV1EditModelConfigRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiConfigV1EditModelConfigRes>(
      {
        url: `/config/model`,
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        data: uniauthGfApiConfigV1EditModelConfigReq,
      },
      options,
    );
  };
  /**
   * @summary 获取配置
   */
  const getConfigModelAll = (
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiConfigV1GetModelConfigRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiConfigV1GetModelConfigRes>(
      { url: `/config/model/all`, method: "GET" },
      options,
    );
  };
  return {
    deleteConfigModel,
    postConfigModel,
    putConfigModel,
    getConfigModelAll,
  };
};
export type DeleteConfigModelResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getConfigModel>["deleteConfigModel"]>>
>;
export type PostConfigModelResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getConfigModel>["postConfigModel"]>>
>;
export type PutConfigModelResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getConfigModel>["putConfigModel"]>>
>;
export type GetConfigModelAllResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getConfigModel>["getConfigModelAll"]>>
>;
