/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 */

import { customApiMutator } from "../utils/api-mutator";
import type {
  DeleteConfigI18nParams,
  GetConfigI18nLangParams,
  UniauthGfApiConfigV1AddI18nItemReq,
  UniauthGfApiConfigV1AddI18nItemRes,
  UniauthGfApiConfigV1DeleteI18ConfigRes,
  UniauthGfApiConfigV1EditI18nItemReq,
  UniauthGfApiConfigV1EditI18nItemRes,
  UniauthGfApiConfigV1FilterI18nReq,
  UniauthGfApiConfigV1FilterI18nRes,
  UniauthGfApiConfigV1GetAllLangsRes,
  UniauthGfApiConfigV1GetI18nConfigRes,
} from "./uniauth.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getConfigI18n = () => {
  /**
   * 删除指定Key的i18n配置项
   * @summary 删除i18n配置
   */
  const deleteConfigI18n = (
    params: DeleteConfigI18nParams,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiConfigV1DeleteI18ConfigRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiConfigV1DeleteI18ConfigRes>(
      { url: `/config/i18n`, method: "DELETE", params },
      options,
    );
  };
  /**
   * 添加一项i18n配置，包含多个语言的翻译
   * @summary 添加i18n项目
   */
  const postConfigI18n = (
    uniauthGfApiConfigV1AddI18nItemReq: UniauthGfApiConfigV1AddI18nItemReq,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiConfigV1AddI18nItemRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiConfigV1AddI18nItemRes>(
      {
        url: `/config/i18n`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: uniauthGfApiConfigV1AddI18nItemReq,
      },
      options,
    );
  };
  /**
   * 编辑一项i18n配置的翻译
   * @summary 编辑i18n项目
   */
  const putConfigI18n = (
    uniauthGfApiConfigV1EditI18nItemReq: UniauthGfApiConfigV1EditI18nItemReq,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiConfigV1EditI18nItemRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiConfigV1EditI18nItemRes>(
      {
        url: `/config/i18n`,
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        data: uniauthGfApiConfigV1EditI18nItemReq,
      },
      options,
    );
  };
  /**
   * 根据关键词筛选i18n配置，支持排序和分页
   * @summary 筛选i18n配置
   */
  const postConfigI18nFilter = (
    uniauthGfApiConfigV1FilterI18nReq: UniauthGfApiConfigV1FilterI18nReq,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiConfigV1FilterI18nRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiConfigV1FilterI18nRes>(
      {
        url: `/config/i18n/filter`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: uniauthGfApiConfigV1FilterI18nReq,
      },
      options,
    );
  };
  /**
   * 获取指定语言的所有翻译配置
   * @summary 获取i18n语言包
   */
  const getConfigI18nLang = (
    params: GetConfigI18nLangParams,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiConfigV1GetI18nConfigRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiConfigV1GetI18nConfigRes>(
      { url: `/config/i18n/lang`, method: "GET", params },
      options,
    );
  };
  /**
   * 获取系统支持的所有语言代码
   * @summary 获取所有支持的语言列表
   */
  const getConfigI18nLangs = (
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiConfigV1GetAllLangsRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiConfigV1GetAllLangsRes>(
      { url: `/config/i18n/langs`, method: "GET" },
      options,
    );
  };
  return {
    deleteConfigI18n,
    postConfigI18n,
    putConfigI18n,
    postConfigI18nFilter,
    getConfigI18nLang,
    getConfigI18nLangs,
  };
};
export type DeleteConfigI18nResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getConfigI18n>["deleteConfigI18n"]>>
>;
export type PostConfigI18nResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getConfigI18n>["postConfigI18n"]>>
>;
export type PutConfigI18nResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getConfigI18n>["putConfigI18n"]>>
>;
export type PostConfigI18nFilterResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getConfigI18n>["postConfigI18nFilter"]>>
>;
export type GetConfigI18nLangResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getConfigI18n>["getConfigI18nLang"]>>
>;
export type GetConfigI18nLangsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getConfigI18n>["getConfigI18nLangs"]>>
>;
