/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 */

import { customApiMutator } from "../utils/api-mutator";
import type {
  UniauthGfApiQuotaPoolV1BatchModifyQuotaPoolReq,
  UniauthGfApiQuotaPoolV1BatchModifyQuotaPoolRes,
  UniauthGfApiQuotaPoolV1ResetBalanceReq,
  UniauthGfApiQuotaPoolV1ResetBalanceRes,
} from "./uniauth.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getQuotapoolAdmin = () => {
  /**
   * @summary 批量修改配额池
   */
  const postQuotaPoolAdminBatchModify = (
    uniauthGfApiQuotaPoolV1BatchModifyQuotaPoolReq: UniauthGfApiQuotaPoolV1BatchModifyQuotaPoolReq,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiQuotaPoolV1BatchModifyQuotaPoolRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiQuotaPoolV1BatchModifyQuotaPoolRes>(
      {
        url: `/quotaPool/admin/batchModify`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: uniauthGfApiQuotaPoolV1BatchModifyQuotaPoolReq,
      },
      options,
    );
  };
  /**
   * @summary 重置配额池
   */
  const postQuotaPoolAdminResetBalance = (
    uniauthGfApiQuotaPoolV1ResetBalanceReq: UniauthGfApiQuotaPoolV1ResetBalanceReq,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiQuotaPoolV1ResetBalanceRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiQuotaPoolV1ResetBalanceRes>(
      {
        url: `/quotaPool/admin/resetBalance`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: uniauthGfApiQuotaPoolV1ResetBalanceReq,
      },
      options,
    );
  };
  return { postQuotaPoolAdminBatchModify, postQuotaPoolAdminResetBalance };
};
export type PostQuotaPoolAdminBatchModifyResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getQuotapoolAdmin>["postQuotaPoolAdminBatchModify"]
    >
  >
>;
export type PostQuotaPoolAdminResetBalanceResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getQuotapoolAdmin>["postQuotaPoolAdminResetBalance"]
    >
  >
>;
