/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 */

import { customApiMutator } from "../utils/api-mutator";
import type {
  GetUserinfosParams,
  UniauthGfApiUserinfosV1FilterReq,
  UniauthGfApiUserinfosV1FilterRes,
  UniauthGfInternalModelEntityUserinfosUserInfos,
} from "./uniauth.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getUserInfo = () => {
  /**
   * 根据UPN，返回用户的所有信息。
   * @summary 查询用户信息
   */
  const getUserinfos = (
    params: GetUserinfosParams,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfInternalModelEntityUserinfosUserInfos>
    >,
  ) => {
    return customApiMutator<UniauthGfInternalModelEntityUserinfosUserInfos>(
      { url: `/userinfos`, method: "GET", params },
      options,
    );
  };
  /**
   * 根据过滤条件，返回用户的所有信息。支持复杂条件查询、排序和分页。
   * @summary 自定义筛选用户信息
   */
  const postUserinfosFilter = (
    uniauthGfApiUserinfosV1FilterReq: UniauthGfApiUserinfosV1FilterReq,
    options?: SecondParameter<
      typeof customApiMutator<UniauthGfApiUserinfosV1FilterRes>
    >,
  ) => {
    return customApiMutator<UniauthGfApiUserinfosV1FilterRes>(
      {
        url: `/userinfos/filter`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: uniauthGfApiUserinfosV1FilterReq,
      },
      options,
    );
  };
  return { getUserinfos, postUserinfosFilter };
};
export type GetUserinfosResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUserInfo>["getUserinfos"]>>
>;
export type PostUserinfosFilterResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUserInfo>["postUserinfosFilter"]>>
>;
