// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package userinfos

import (
	"uniauth-gf/api/userinfos"
)

type ControllerV1 struct{}

func NewV1() userinfos.IUserinfosV1 {
	return &ControllerV1{}
}
