name: Gosec 安全检查
on:
  push:
    branches: main
    paths:
      - 'uniauth-gf/**'
  pull_request:
    paths:
      - 'uniauth-gf/**'
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          cache: true
          cache-dependency-path: uniauth-gf/go.sum
          go-version: "1.25.0"
      - name: Install Gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Run Gosec Security Scanner
        working-directory: ./uniauth-gf
        run: gosec ./...
